websocket:
  server:
    port: 3333

server:
  port: 8091

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/netty_chatroom?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ro(mysql用户名)
    password: 1367(mysql密码)

mybatis:
  mapper-locations: classpath*:mapper/*.xml
